Demzne 3170 decentralize eosdac updateconfig action
Alien-Worlds/eosdac-contracts pull request #134
Opened 2024-03-18 14:55 UTC by angelol

Additional checks TBD

2024-03-19 09:43 UTC, dallasjohnson requested changes
LGTM. Only a couple of small suggestions

2024-03-19 09:43 UTC, dallasjohnson commented on contracts/daccustodian/config.cpp
> +        "ERR::SETMAXVOTES_INVALID_VALUE::The number of max votes must be less than the number of elected candidates.");
I think this should be less than half the `numelected` eg. if numelected == 5 this should be < 2.5. This will have a related effect on setting `numelected`

2024-03-19 09:43 UTC, dallasjohnson commented on contracts/daccustodian/config.cpp
> +    check(numelected >= globals.get_maxvotes(),
For the same reason above this should > (2 * maxvotes). The reason is that this forces a whale to split the bags to be able to vote for a controlling majority of custodians.

2024-03-19 09:43 UTC, dallasjohnson commented on contracts/daccustodian/config.cpp
> +    check(periodlength <= 24 * 60 * 60 * 3 * 365,
Maybe we should cap this to 6 months (which is even very very long).

2024-03-19 12:51 UTC, angelol commented on contracts/daccustodian/config.cpp
> +        "ERR::SETMAXVOTES_INVALID_VALUE::The number of max votes must be less than the number of elected candidates.");
Done

2024-03-19 12:52 UTC, angelol commented on contracts/daccustodian/config.cpp
> +    check(numelected >= globals.get_maxvotes(),
Done

2024-03-19 12:53 UTC, angelol commented on contracts/daccustodian/config.cpp
> +    check(periodlength <= 24 * 60 * 60 * 3 * 365,
Done

2024-03-20 06:55 UTC, dallasjohnson approved these changes
LGTM 👍

2024-03-26 12:23 UTC, merged