Period budget
Alien-Worlds/eosdac-contracts pull request #24
Opened 2022-03-17 18:25 UTC by angelol

This intends to implement the ticket 'Inline action to transfer DAO period budget for DAO budget throttling'

Feedback much appreciated!

2022-03-18 04:27 UTC, dallasjohnson requested changes

2022-03-18 04:27 UTC, dallasjohnson commented on contracts/daccustodian/newperiod_components.cpp
> +    auto       nftcache   = nftcache_table{get_self(), get_self().value};
As a general pattern in all the DAC specific tables, the scope has been to save to the `dac_id` rather than `get_self()`. This has effectively given us 2 primary keys in each table. dac_id + nft_id (in this case) when searching. 
To make that work in this case we would need to lookup the `dac_id` from the `index.worlds` `dacs` table. assuming the owner is the account that should be the matching owner here for the NFT.

As an aside, Maybe should consider removing AUTH from the dacs table and just rely on having a unique `owner` for each DAC instead. I just noticed there is a bit of a duplication of data there.

2022-03-18 04:27 UTC, dallasjohnson commented on contracts/daccustodian/newperiod_components.cpp
> +    const auto nftcache = nftcache_table{get_self(), get_self().value};
Should be scoped to dac_id for the current dac.

2022-03-18 04:27 UTC, dallasjohnson commented on contracts/daccustodian/daccustodian.hpp
> +        name     owner;
I think this should have the NFT id as the primary key. The owner could have multiple NFTs and will collide. Also by moving to scope this table to the dac_id (as mentioned in another comment) this field becomes redundant.

2022-03-18 04:27 UTC, dallasjohnson commented on contracts/daccustodian/daccustodian.hpp
> +        uint16_t percentage;
In order to make the NFT cache generalised for other NFT features later (eg. we may have an NFT template that unlocks advanced worker proposals (boolean value) and another to change the number of elected custodians (integer value)) then possibly have the percentage field be reusable "value" field instead. Then we could add a new index for the table to combine the templateID with the value. This would give us case-specific searching when needed that could we use to manipulate the indexing sort results. eg. combine budgetTemplateId & (100 -percentageValue) will ensure the highest percentage NFT is always first in the results when searching for (nft_id & 0000) in the secondary index. Then the same pattern can be applied for other templateIDs with associated value fields. Hopefully all that makes sense.

2022-03-18 09:09 UTC, angelol commented on contracts/daccustodian/daccustodian.hpp
> +        uint16_t percentage;
Then how about a std::map? We can store any future NFT data in it without needing to change the table.

2022-03-18 09:11 UTC, angelol commented on contracts/daccustodian/newperiod_components.cpp
> +        // DAC owns more than one NFT, the situation is not well-defined, do nothing
I thought about directly querying the AA tables. I cannot filter by collection or schema though and that would potentially be a denial of service attack if the user own many NFTs, since I need to loop through all of them. So caching in our own table really is the only way IMHO.

2022-03-18 09:44 UTC, angelol commented on contracts/daccustodian/daccustodian.hpp
> +        uint16_t percentage;
Or instead of copying the data into our own table, we just read it from the AA table. We will still need a cache table in order to be able to query the nft_id though due to lack of useful indexes on AA.

2022-03-18 10:53 UTC, angelol commented on contracts/daccustodian/daccustodian.hpp
> +        uint16_t percentage;
(100 - percentageValue) works since I know the range of the expected values. If value is a generic field that could be more than just percentage, this does not work, or does it? Perhaps just combining normally and use the reverse iterator if necessary?

2022-03-18 12:09 UTC, dallasjohnson commented on contracts/daccustodian/newperiod_components.cpp
> +        // DAC owns more than one NFT, the situation is not well-defined, do nothing
Yes, after thinking it through and seeing the lack of indexes on AA I think you're exactly right.

2022-03-18 12:21 UTC, dallasjohnson commented on contracts/daccustodian/daccustodian.hpp
> +        uint16_t percentage;
I don't think reverse iterator would work (at least not easily). You would need to find the max value or the first of the next template and then iterate in reverse. eg. reverse iterator on template id 1234 with an arbitrary max value of a Uint32 would be something like Uint64(1234 << 32 | Uint32.Max). I guess that could work. Is that what your were thinking?

2022-03-18 12:39 UTC, angelol commented on contracts/daccustodian/newperiod_components.cpp
> +    check(nft.schema_name == BUDGET_SCHEMA, "Wrong schema! Is %s but expected %s", nft.schema_name, BUDGET_SCHEMA);
OK

2022-03-18 12:41 UTC, angelol commented on contracts/daccustodian/newperiod_components.cpp
> +    auto       nftcache   = nftcache_table{get_self(), get_self().value};
If AUTH account can be considered always to be identical to dac.owner, that makes sense, I'll remove it.

Regarding looking up the dac in the dacs table, the owner is not enforced to be unique, so theoretically the same owner could own multiple dacs. Should we try to prevent this somehow?

2022-03-18 12:57 UTC, dallasjohnson commented on contracts/daccustodian/newperiod_components.cpp
> +    auto       nftcache   = nftcache_table{get_self(), get_self().value};
Yes, Initially on EOSDAC we wanted to allow an owner to "own" multiple dacs but I think it makes sense to lock it down to one DAC per Auth/owner account. That will make it easier to use NFTs to unlock features owned by the owner. We are limiting multiple DACs from sharing the same symbol in `regdac` so a similar approach could be taken for the owner.

2022-03-22 18:02 UTC, angelol commented on contracts/daccustodian/newperiod_components.cpp
> +    auto       nftcache   = nftcache_table{get_self(), get_self().value};
AUTH is removed and replaced by dac.owner everywhere. Owner is now enforced to be unique.

2022-03-22 18:02 UTC, angelol commented on contracts/daccustodian/newperiod_components.cpp
> +    const auto nftcache = nftcache_table{get_self(), get_self().value};
Done

2022-03-22 18:02 UTC, angelol commented on contracts/daccustodian/daccustodian.hpp
> +        name     owner;
Done

2022-03-22 18:05 UTC, angelol commented on contracts/daccustodian/daccustodian.hpp
> +        uint16_t percentage;
Done. You were right, your suggestion was the best, however with Uint64.Max instead of 100 🙂

2022-03-23 02:12 UTC, dallasjohnson requested changes
The changes look great. Thank you but I have a couple of new suggestions in there which I hadn't thought about before. Sorry.

2022-03-23 02:12 UTC, dallasjohnson commented on contracts/daccustodian/newperiod_components.cpp
> +            x.template_id = nft.template_id;
As mentioned earlier this needs to be changed to refer to the schema. For now, that will always be BUDGET but could be generalised later.

Just another annoying thought - so this mechanism could be generalised across the DAC contracts to unlock other features, do you think it's worth considering moving it into the one contract that should never change between different DACs and that is `dacdirectory`. All the smart contracts have an implicit reference to this and it acts as the central places for accounts and features. IMHO it would make sense to store this generalised NFT feature toggle there too. Then we can incrementally add new schema types to the same NFTCache mechanism.

2022-03-23 18:23 UTC, angelol commented on contracts/daccustodian/daccustodian.hpp
> +        int32_t  template_id;
No problem, DONE

2022-03-23 18:23 UTC, angelol commented on contracts/daccustodian/newperiod_components.cpp
> +            x.template_id = nft.template_id;
DONE

2022-03-23 18:24 UTC, angelol commented
Really no need to apologize. I know how the creative process works. Happy to change even more stuff around if you get more good ideas! 👍

2022-03-24 03:52 UTC, dallasjohnson approved these changes
Small change/suggestion in there but not required if you don't think it matters or is better as it is. Looks great. Thanks

2022-03-24 03:52 UTC, dallasjohnson commented on contract-shared-headers/config.hpp
> +static constexpr int32_t BUDGET_TEMPLATE_ID{1};
I don't think we need the template id anymore if we are using the schema instead in the code functionality.

2022-03-24 03:52 UTC, dallasjohnson commented on contracts/dacdirectory/dacdirectory.cpp
> +                    auto       nftcache  = nftcache_table{DACDIRECTORY_CONTRACT, old_dac.dac_id.value};
Not really a big deal but generally you would follow the pattern of `get_self()` instead of the `DACDIRECTORY_CONTRACT` here so the code is more portable but given the `DACDIRECTORY_CONTRACT` value is compiled into the artefact this might be better as is.

2022-03-24 08:30 UTC, angelol commented on contract-shared-headers/config.hpp
> +#define DACDIRECTORY_CONTRACT_STR "dacdirectory"
It was hardcoded before also, I just changed it from using magic strings that were copied and pasted throughout the code to a config value. I think the reason why the original author did it is that the `struct [[eosio::table("dacs"), eosio::contract(DACDIRECTORY_CONTRACT_STR)]]` macro requires a static char[] and the tables in the header are defined outside of the contract so we can't use get_self() here. I still think it's a good thing to have it configurable, let me try something…

2022-03-24 08:37 UTC, angelol commented on contract-shared-headers/config.hpp
> +static constexpr int32_t BUDGET_TEMPLATE_ID{1};
Good catch, removed

2022-03-24 08:38 UTC, angelol commented on contracts/dacdirectory/dacdirectory.cpp
> +                    auto       nftcache  = nftcache_table{DACDIRECTORY_CONTRACT, old_dac.dac_id.value};
You're absolutely right, no reason to use anything other than get_self() in this case. What was I thinking? 🤦‍♂️ 

DONE

2022-03-24 08:53 UTC, angelol commented on contract-shared-headers/config.hpp
> +#define DACDIRECTORY_CONTRACT_STR "dacdirectory"
After thinking about this a little bit, it's not possible to make everyting configurable. The dacdirectory contract needs to be hardcoded, otherwise, the other contracts have no way of knowing where to look for the directory. So we're gonna have to leave it as it is. Everything else can still be configurable in the directory.

2022-03-24 09:11 UTC, dallasjohnson commented on contract-shared-headers/config.hpp
> +#define DACDIRECTORY_CONTRACT_STR "dacdirectory"
Yes true. The whole point of the dacdirectory was to create a central contract that could configure the connection configs of all the others. Not everything can be configurable.

2022-03-24 09:20 UTC, merged