Extract budget transfer
Alien-Worlds/eosdac-contracts pull request #25
Opened 2022-04-22 11:02 UTC by angelol

This PR intends to implement ticket "Extract the budget transfer from NewPeriod action into explicit claim action" (https://app.clickup.com/t/24ga0jf )

Remarks:

- I thought a more type-safe data format for the state2 std::map would be better, so chose to use a variant instead of int64_t to store the values. It should have minimal overhead (if at all) but it generates more reliable and more easily maintainable code IMHO.
- While working with the code, I realized we could automatically migrate the data when it's accessed for the first time. This simplifies the deployment as calling the `migratedata` action is no longer necessary. I left the migratedata action in so one can still manually migrate dacs from the outside (dacs that are inactive etc.).

2022-04-28 05:52 UTC, dallasjohnson requested changes
Looks great. I've only got one suggestion but it does mean writing more code so if you think it's a bad idea.

Only one other thought; You mention auto-migrating when the state is first read. Could this potentially cause RAM errors if it consumes more RAM than the original table? Not sure if you have tested that but it can be easy to miss in the Lamington test env.

2022-04-28 05:52 UTC, dallasjohnson commented on contracts/daccustodian/daccustodian.hpp
> +
I really like the `std::map` approach with the `state_value_variant`. It definitely creates flexibility with type safety. However, it does push some of type-safety work onto the users of the code elsewhere in the code outside on this definition. Can suggest creating custom setters and getters for each of the properties. Then it would have type-safety for the consumers of the table. eg. Add methods to `contr_state2` as 
` int64_t total_weight_of_votes() { return *this.get<int64_t>(state_keys::total_weight_of_votes); }`
and 
`void set_total_weight_of_votes(int64_t new_value) { *this.set(state_keys::set_total_weight_of_votes, new_value);}`

This code is probably not quite right but hopefully conveys this idea. The main point would be to encapsulate the set/get logic inside this struct like done in some languages eg. Java or Objective C.

2022-04-28 06:05 UTC, angelol commented
RAM errors can only happen when using same_payer while not currently having the authorization of the original ram payer. Since the RAM payer is always get_self(), we're safe.

2022-04-28 06:08 UTC, angelol commented on contracts/daccustodian/daccustodian.hpp
> +
I thought about creating custom getters and setters. Left off on implementing those for now. But I'm glad you like that approach. It will make using this code much easier and more safe. Will get on it.

2022-04-28 08:06 UTC, dallasjohnson commented
Ah. That makes sense. While writing the original DAC code we were focused on getting someone else to pay for the RAM because they were meant to be open for an unlimited number of DACs. So I still think of RAM in that way.

2022-04-28 09:39 UTC, dallasjohnson commented on contracts/daccustodian/daccustodian.hpp
> +
Just thinking to keep the code clean using a Macro might help for the setter/getters like:
`#define PROPERTY(TYPE, NAME, DEFAULT_VALUE)                                                                            \
    TYPE NAME = DEFAULT_VALUE;                                                                                         \
    TYPE get_##NAME() const { return NAME; }                                                                           \
    void set_##NAME(TYPE _) { NAME = (_); }
`

2022-05-05 10:54 UTC, dallasjohnson approved these changes

2022-05-05 10:54 UTC, merged